### ISSUE TITLE
`sentry` in SapphireClientOptions is missing

### ISSUE THREAD

**Issue by some1chan** [kaname-png/neko-plugins#222]
Bringing this out of the Sapphire Discord, into here:

I've recently updated my Sapphire project into TypeScript 5.2, and I've changed `module` and `moduleResolution` in my `tsconfig.json` to `node16` to fix issues. However, my original way of getting `SentryOptions` into `SapphireClientOptions` no longer seems to work.

```ts
// setup.ts

// ... (a bunch of imports)
import '@kaname-png/plugin-sentry/register';
import type { SentryOptions } from '@kaname-png/plugin-sentry/dist/lib/types';
// Errors with "Cannot find module '@kaname-png/plugin-sentry/dist/lib/types' or its corresponding type declarations.ts(2307)"

// ... (actual code)

declare module '@sapphire/framework' {
    interface SapphireClientOptions {
        sentry?: { options?: SentryOptions };
    }
}
```

Going off of Favna in the Sapphire Discord, it may be because the [export mappings need fixing?](https://discord.com/channels/737141877803057244/1144063656166953021/1144673917949186060/) Help would be appreciated!

My current `tsconfig.json`:
```json
{
	"compilerOptions": {
		"lib": ["ESNext"],
		"target": "ESNext",
		"module": "Node16",
		"baseUrl": "src",
		"rootDir": "src",
		"outDir": "dist",
		"paths": { "#lib/*": ["lib/*"], "#root/*": ["*"] },

		// Comes from @sapphire/ts-config ish
		"allowSyntheticDefaultImports": true,
		"alwaysStrict": true,
		"declaration": true,
		"declarationMap": true,
		"emitDecoratorMetadata": true,
		"esModuleInterop": true,
		"experimentalDecorators": true,
		"importHelpers": true,
		"verbatimModuleSyntax": true,
		"incremental": true,
		"moduleResolution": "node16",
		"newLine": "lf",
		"noEmitHelpers": false,
		"noFallthroughCasesInSwitch": true,
		"noImplicitReturns": true,
		"noUnusedLocals": true,
		"noUnusedParameters": true,
		"preserveConstEnums": true,
		"pretty": true,
		"removeComments": false,
		"resolveJsonModule": true,
		"sourceMap": true,
		"strict": true,
		"useDefineForClassFields": true
	},
	"include": ["src/**/*", "src/**/*.json"],
	"exclude": ["node_modules", "dist", "**/*.test.ts", "**/*.spec.ts"]
}
```

**Comment by sawa-ko** [comment]
Try with [1.2.0](https://github.com/kaname-png/neko-plugins/compare/@kaname-png/plugin-sentry@1.1.0...@kaname-png/plugin-sentry@1.2.0) version

**Comment by some1chan** [comment]
Sorry for the wait; this doesn't seem to have fixed it for me.

I've linked a reproduction repository, that should help with debugging: https://github.com/some1chan/plugin-sentry-repro

I'm using ES modules, Node.js 18.17.1, and pnpm v8.7.5.
